In [33]:
import requests
import pandas as pd
from time import sleep

In [6]:
r = requests.get("https://www.census.gov/cgi-bin/geo/shapefiles/getFile.php?&VAR=2023|DTRACT|Ftl_2023_01_tract.zip")

In [12]:
import requests, zipfile, io
zip_file_url = "https://www2.census.gov/geo/tiger/TIGER2023/TRACT/tl_2023_01_tract.zip"
r = requests.get(zip_file_url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall("/home/tonydeals/app/maps/shapefiles/2023/01")

In [35]:
fips_codes = [ '49',
 '50',
 '78',
 '51',
 '53',
 '54',
 '55',
 '56']

In [36]:
for code in fips_codes:
    sleep(5)
    zip_file_url = f"https://www2.census.gov/geo/tiger/TIGER2023/TRACT/tl_2023_{code}_tract.zip"
    r = requests.get(zip_file_url)
    z = zipfile.ZipFile(io.BytesIO(r.content))
    z.extractall(f"/home/tonydeals/app/maps/shapefiles/2023/{code}")
    print(f"tracts downloaded for state {code}")

tracts downloaded for state 49
tracts downloaded for state 50
tracts downloaded for state 78
tracts downloaded for state 51
tracts downloaded for state 53
tracts downloaded for state 54
tracts downloaded for state 55
tracts downloaded for state 56

In [15]:
y = """
    def handle(self, *args, **options):
        new_state = State(
            id = 1,
            name = "Alabama"
        )
        new_state.save()
    

        new_state = State(
            id = 2,
            name = "Alaska"
        )
        new_state.save()
    

        new_state = State(
            id = 60,
            name = "American Samoa"
        )
        new_state.save()
    

        new_state = State(
            id = 4,
            name = "Arizona"
        )
        new_state.save()
    

        new_state = State(
            id = 5,
            name = "Arkansas"
        )
        new_state.save()
    

        new_state = State(
            id = 6,
            name = "California"
        )
        new_state.save()
    

        new_state = State(
            id = 8,
            name = "Colorado"
        )
        new_state.save()
    

        new_state = State(
            id = 9,
            name = "Connecticut"
        )
        new_state.save()
    

        new_state = State(
            id = 10,
            name = "Delaware"
        )
        new_state.save()
    

        new_state = State(
            id = 11,
            name = "District of Columbia"
        )
        new_state.save()
    

        new_state = State(
            id = 12,
            name = "Florida"
        )
        new_state.save()
    

        new_state = State(
            id = 13,
            name = "Georgia"
        )
        new_state.save()
    

        new_state = State(
            id = 66,
            name = "Guam"
        )
        new_state.save()
    

        new_state = State(
            id = 15,
            name = "Hawai ªi"
        )
        new_state.save()
    

        new_state = State(
            id = 16,
            name = "Idaho"
        )
        new_state.save()
    

        new_state = State(
            id = 17,
            name = "Illinois"
        )
        new_state.save()
    

        new_state = State(
            id = 18,
            name = "Indiana"
        )
        new_state.save()
    

        new_state = State(
            id = 19,
            name = "Iowa"
        )
        new_state.save()
    

        new_state = State(
            id = 20,
            name = "Kansas"
        )
        new_state.save()
    

        new_state = State(
            id = 21,
            name = "Kentucky"
        )
        new_state.save()
    

        new_state = State(
            id = 22,
            name = "Louisiana"
        )
        new_state.save()
    

        new_state = State(
            id = 23,
            name = "Maine"
        )
        new_state.save()
    

        new_state = State(
            id = 24,
            name = "Maryland"
        )
        new_state.save()
    

        new_state = State(
            id = 25,
            name = "Massachusetts"
        )
        new_state.save()
    

        new_state = State(
            id = 26,
            name = "Michigan"
        )
        new_state.save()
    

        new_state = State(
            id = 27,
            name = "Minnesota"
        )
        new_state.save()
    

        new_state = State(
            id = 28,
            name = "Mississippi"
        )
        new_state.save()
    

        new_state = State(
            id = 29,
            name = "Missouri"
        )
        new_state.save()
    

        new_state = State(
            id = 30,
            name = "Montana"
        )
        new_state.save()
    

        new_state = State(
            id = 31,
            name = "Nebraska"
        )
        new_state.save()
    

        new_state = State(
            id = 32,
            name = "Nevada"
        )
        new_state.save()
    

        new_state = State(
            id = 33,
            name = "New Hampshire"
        )
        new_state.save()
    

        new_state = State(
            id = 34,
            name = "New Jersey"
        )
        new_state.save()
    

        new_state = State(
            id = 35,
            name = "New Mexico"
        )
        new_state.save()
    

        new_state = State(
            id = 36,
            name = "New York"
        )
        new_state.save()
    

        new_state = State(
            id = 37,
            name = "North Carolina"
        )
        new_state.save()
    

        new_state = State(
            id = 38,
            name = "North Dakota"
        )
        new_state.save()
    

        new_state = State(
            id = 69,
            name = "Northern Mariana Islands"
        )
        new_state.save()
    

        new_state = State(
            id = 39,
            name = "Ohio"
        )
        new_state.save()
    

        new_state = State(
            id = 40,
            name = "Oklahoma"
        )
        new_state.save()
    

        new_state = State(
            id = 41,
            name = "Oregon"
        )
        new_state.save()
    

        new_state = State(
            id = 42,
            name = "Pennsylvania"
        )
        new_state.save()
    

        new_state = State(
            id = 72,
            name = "Puerto Rico"
        )
        new_state.save()
    

        new_state = State(
            id = 44,
            name = "Rhode Island"
        )
        new_state.save()
    

        new_state = State(
            id = 45,
            name = "South Carolina"
        )
        new_state.save()
    

        new_state = State(
            id = 46,
            name = "South Dakota"
        )
        new_state.save()
    

        new_state = State(
            id = 47,
            name = "Tennessee"
        )
        new_state.save()
    

        new_state = State(
            id = 48,
            name = "Texas"
        )
        new_state.save()
    

        new_state = State(
            id = 74,
            name = "U.S. Minor Outlying Islands"
        )
        new_state.save()
    

        new_state = State(
            id = 49,
            name = "Utah"
        )
        new_state.save()
    

        new_state = State(
            id = 50,
            name = "Vermont"
        )
        new_state.save()
    

        new_state = State(
            id = 78,
            name = "Virgin Islands (U.S.)"
        )
        new_state.save()
    

        new_state = State(
            id = 51,
            name = "Virginia"
        )
        new_state.save()
    

        new_state = State(
            id = 53,
            name = "Washington"
        )
        new_state.save()
    

        new_state = State(
            id = 54,
            name = "West Virginia"
        )
        new_state.save()
    

        new_state = State(
            id = 55,
            name = "Wisconsin"
        )
        new_state.save()
    

        new_state = State(
            id = 56,
            name = "Wyoming"
        )
        new_state.save()
    """

In [30]:
fips_codes = []
for z in y.split("id = ")[1:]:
    code = z.split(",")[0]
    if len(code) == 1:
        code = "0" + code
    fips_codes += [code]
fips_codes

['01',
 '02',
 '60',
 '04',
 '05',
 '06',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '66',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '69',
 '39',
 '40',
 '41',
 '42',
 '72',
 '44',
 '45',
 '46',
 '47',
 '48',
 '74',
 '49',
 '50',
 '78',
 '51',
 '53',
 '54',
 '55',
 '56']